#local
location: @PATH_TO_requests.csv@
maxlatitude: -11.12
maxlongitude: -76.44
minlatitude: -12.92
minlongitude: -80.42
rms: 0
output: @PATH_TO_final_output.csv@
timebinsize: 20
loglevel: INFO
logfile: ../log.txt
#preprod
#location: URL_TO_PREPROD/requests.csv